# Generated by Django 3.1.3 on 2021-08-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('message', models.CharField(max_length=50, verbose_name='tweet message')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
            ],
        ),
    ]
